### PR TITLE
Localization implementation

### PR DESCRIPTION
**Pull request by Mixu78**
This adds a language selector to the home screen as well as translations to almost all user-facing strings.

This PR should be merged after #3

### CODE REVIEW

**Comment by Mixu78** [comment]
The version should probably be bumped however I don't know how that should be done

**Comment by ahnl** [comment]
I pushed a few commits to fix the UI. 

The language selector used to be under window buttons on MacOS and was pushing configuration menu button down. I moved the selector next to the config button and added a few more stylings to it.

<details>
<summary>Before</summary>

</details>

image

**Review by ahnl — APPROVED** [review]
It looks like this commit contains everything from #3. We'll merge this larger PR and close the other one?

Thank you for this big contribution! It is surely useful and it is awesome to have localisations in all three languages. 🥇

**Comment by Mixu78** [comment]
#3 can be closed, it should be identical to this except for the translation implementation.

**Pull request merged**
